### ISSUE TITLE
java.lang.UnsupportedOperationException: Compound units not supported

### ISSUE THREAD

**Issue by racc** [unitsofmeasurement/uom-se#122]
Hi there,

I get an error when parsing Quantities using the QuantityFormat class:
e.g. 
	`ComparableQuantity<?> parsed1 = QuantityFormat.getInstance().parse("60 m");`

This throws:
Exception in thread "main" java.lang.UnsupportedOperationException: Compound units not supported
	at tec.uom.se.internal.format.LocalUnitFormatParser.CompoundExpr(LocalUnitFormatParser.java:76)
	at tec.uom.se.internal.format.LocalUnitFormatParser.parseUnit(LocalUnitFormatParser.java:68)
	at tec.uom.se.format.LocalUnitFormat.parse(LocalUnitFormat.java:232)
	at tec.uom.se.format.LocalUnitFormat.parse(LocalUnitFormat.java:250)
	at tec.uom.se.format.NumberSpaceQuantityFormat.parse(NumberSpaceQuantityFormat.java:75)
	at tec.uom.se.format.NumberSpaceQuantityFormat.parse(NumberSpaceQuantityFormat.java:81).

I am using uom-se-0.8, and unit-api-0.8.

Cheers,
Jason

**Comment by racc** [comment]
Also related, if I try 
`ComparableQuantity<?> parsed2 = QuantityFormat.getInstance(NumberFormat.getInstance(), SimpleUnitFormat.getInstance()).parse("60 m");`

Then I get the error:
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at tec.uom.se.quantity.Quantities.getQuantity(Quantities.java:95)
	at tec.uom.se.format.NumberSpaceQuantityFormat.parse(NumberSpaceQuantityFormat.java:76)
	at tec.uom.se.format.NumberSpaceQuantityFormat.parse(NumberSpaceQuantityFormat.java:81)
	at test.Bug.main(Bug.java:40)

**Comment by keilw** [comment]
Have to look into it. At first sight, it should also use `SimpleUnitFormat` inside `QuantityFormat` by default.
