### ISSUE TITLE
SimpleUnitFormat produces uninformative error message

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#133]
See https://github.com/unitsofmeasurement/uom-systems/issues/49 This is not a Unit System problem.

**Comment by keilw** [comment]
It may not be the nicest message, but now `ParserException.getParsedString()` is returned inside an `IllegalArgumentException`. Resulting in:
`Exception in thread "main" java.lang.IllegalArgumentException: d not recognized (in 300 d at index 4)
	at tec.uom.se.quantity.Quantities.getQuantity(Quantities.java:80)
	at tec.uom.demo.se.QuantityFormatDemo.main(QuantityFormatDemo.java:51)`
An actual `IllegalArgumentException` does not need to be rethrown, so it would go through in that case now. Will be fixed with 1.0.2
