### ISSUE TITLE
Quantities are not serializable

### ISSUE THREAD

**Issue by mk-fhnw** [unitsofmeasurement/uom-se#96]
Quantities are currently not serializable (e.g. tec.uom.se.quantity.NumberQuantity; no valid constructor).
Assuming that either AbstractQuantity is missing a no-args constructor or interface Serializable.

Code to test:
public static void main(String[] args) throws IOException, ClassNotFoundException {
	byte[] serialized = serialize(Quantities.getQuantity(0, Units.JOULE));
	Object obj = deserialize(serialized);
	ComparableQuantity<?> quantity = (ComparableQuantity<?>)obj;
}
public static Object deserialize(byte[] serialized) throws IOException, ClassNotFoundException {
	ByteArrayInputStream bis = new ByteArrayInputStream(serialized);
	ObjectInputStream ois = new ObjectInputStream(bis);
	Object obj = ois.readObject();
	ois.close();
	return obj;
}
public static byte[] serialize(ComparableQuantity<?> quantity) throws IOException {
	ByteArrayOutputStream bos = new ByteArrayOutputStream();
	ObjectOutputStream oos = new ObjectOutputStream(bos);
	oos.writeObject(quantity);
	bos.close();
	return bos.toByteArray();
}

**Comment by keilw** [comment]
NumberQuantity is Serializable. AbstractQuantity could also implement it in theory, but Quantity on the API level can't. Since Serializable is not supported by Java ME. 
No-op constructors are quite problematic regarding immutability. Concrete classes like NumberQuantity (though not final) are not supposed to have mutable elements, thus a no-op constructor would be quite problematic with that respect.

**Comment by keilw** [comment]
After adding Serializable to ComparableQuantity you get:

Exception in thread "main" java.io.NotSerializableException: tec.uom.se.unit.ProductUnit$Element
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at tec.uom.demo.se.SerialDemo.serialize(SerialDemo.java:34)
	at tec.uom.demo.se.SerialDemo.main(SerialDemo.java:16)

Looks like relevant Unit implementations also have to be explored further.

**Comment by keilw** [comment]
Making ProductUnit.Element serializable, it works. We have to scan other Unit subclasses for similar inner classes that may not be serializable. Note, this likely won't be supported by the RI for ME/SE cross-compatibility.

**Comment by mk-fhnw** [comment]
Solves the issue only partially. Using derived units leads to java.io.NotSerializableException: tec.uom.se.function.RationalConverter

Code below works when using Units.SECOND but fails when using Units.HOUR:
public static void main(String[] args) throws IOException, ClassNotFoundException {
byte[] serialized = serialize(Quantities.getQuantity(1, Units.HOUR));
Object obj = deserialize(serialized);
ComparableQuantity<?> quantity = (ComparableQuantity<?>)obj;
System.out.println(quantity);
}
public static Object deserialize(byte[] serialized) throws IOException, ClassNotFoundException {
ByteArrayInputStream bis = new ByteArrayInputStream(serialized);
ObjectInputStream ois = new ObjectInputStream(bis);
Object obj = ois.readObject();
ois.close();
return obj;
}
public static byte[] serialize(ComparableQuantity<?> quantity) throws IOException {
ByteArrayOutputStream bos = new ByteArrayOutputStream();
ObjectOutputStream oos = new ObjectOutputStream(bos);
oos.writeObject(quantity);
bos.close();
return bos.toByteArray();
}

**Comment by keilw** [comment]
Will see, if either the concrete converters or AbstractConverter could also be made Serializable in the SE/OpenJDK implementation.
Thanks

**Comment by keilw** [comment]
All converters implement Serializable now. SerialDemo works for HOUR. Will close, please reopen or file new ticket should you come across something else. Thanks
